# site settings

title: Ömer Yel
description: About Me
taglong: My Personal Website
tagshort: Personal Website
url: omeryel@github.io
baseurl: ""
permalink: pretty
repo: https://github.com/omeryel/omeryel.github.io

# author settings

author:
  name: Ömer Yel
  email: omeryel54@gmail.com
photo: /assets/photo.jpg

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
